---
title: "Example Analysis"
author: "Hena R. Ramay"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    theme: yeti
    highlight: kate
    toc: true
    toc_float: 
      collapsed: false
    toc_depth: 4
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,message = F,warning = F,fig.height = 5,fig.width = 7)
library(tidyverse)
library(limma)
library(knitr)
library(DT)

# This helper function file has all the necessary functions for this analysis
source("dAA_helper_functions.R")


# A file containing species information. Species as rows and samples as columns

species_annot<-read.csv("example/merged_species_table.csv")
# colnames(species_annot)<-strsplit2(colnames(species_annot),split = "[.]")[,1]
# species_annot<-species_annot[,-grep(pattern = "unmatched|TSNeg|TSZymo|TSZYMO",x = colnames(species_annot))]
# 
# species_annot$clade_name<-strsplit2(species_annot$clade_name,split = "[|]")[,7]
# write.csv(x = species_annot,file = "example/merged_species_table.csv",row.names = F)

otu<-species_annot %>% select(-clade_taxid)
rownames(otu)<-otu$clade_name

otu_table<-otu %>% filter(clade_name !="UNKNOWN" & clade_name !="unclassified") %>% select(-clade_name)


# Make sure row names in metadata are sample names as in species table

meta_data<-read.csv("example/TS_metadata.txt",sep = "\t",stringsAsFactors = T)
 rownames(meta_data)<-meta_data$Sample


## You can add up to two fixed variables from the metadata file
fixed_vars=c("Status","Sex")
#fixed_vars="Status"
#Directory where results from each method are saved and the combined tables are saved too.


output_dir="TS"
output_taxa=paste0(output_dir,"/taxa_results")
output_pathabund=paste0(output_dir,"/pathabund_results")
output_genefamilies=paste0(output_dir,"/genefamilies_results")

dir.create(output_dir)
dir.create(output_taxa)
dir.create(output_pathabund)
dir.create(output_genefamilies)
## Wrapper_daa is the main function that calles all the methods. 
## IMPORTANT make sure you chose appropriate min_abun and min_prev
output <-
    wrapper_daa(
        min_abun = 2800,
        min_prev = 0.1,
        metadata = meta_data,
        ASV_table = otu_table,
        fixed_vars = fixed_vars,
        rand_vars = NULL,
        output_dir=output_taxa
    )

write.csv(output,file = paste0(output_dir,"/dAA_microbe_ouput.csv"))


```



```{r}
datatable(output)
```



## Pathway Abundance

```{r,results='hide'}


remove_rows=c("UNMAPPED","UNINTEGRATED","UNGROUPED")

path_abund<-read.csv("example/merged_pathabundance_unstratified.tsv",sep="\t") %>% filter(!(X..Pathway %in% remove_rows) )

path_abund<-path_abund[,-grep(pattern = "unmatched|TSNeg|TSZymo|TSZYMO",x = colnames(path_abund))]

rownames(path_abund)<-path_abund$X..Pathway
path_abund<-path_abund %>% select(-X..Pathway)
path_abund<-path_abund[rowSums(path_abund) >0,]
colnames(path_abund)<-strsplit2(x = colnames(path_abund),split = "[.]")[,1]


```

### TS status

```{r,results='hide'}
ASV_table<-path_abund %>%mutate(across(where(is.numeric), as.integer))
rownames(ASV_table)<-gsub("[[:punct:]]", "_", rownames(ASV_table))
rownames(ASV_table)<-gsub(" ", "", rownames(ASV_table))

output <- wrapper_daa(min_abun = 0,min_prev = 0.01,metadata = meta_data,ASV_table,fixed_vars = fixed_vars,rand_vars=NULL,output_dir = output_pathabund)


write.csv(output_dir,file = paste0(output_dir,"/dAA_pathway_abundance_output.csv"))

```

```{r}
datatable(output)
```
